### ISSUE TITLE
Repo ownership & maintenance status – migrating to react-native-community or a new owner

### ISSUE THREAD

**Issue by wamry** [luggit/react-native-config#382] opened 2019-08-20 14:38 UTC
After going through tons of issues and trying every possible way to get this awful messy repo to work, I tried to work with this "https://github.com/luggit/react-native-config.git#89a602b" and the npm version, it just won't work, **does anyone have have a stable fork that i can use ?**

i'm using react-native 0.60.5

**Comment by tadaniya** [comment] 2019-08-21 06:46
I'm also looking for that problem.
I tried to use `react-native-dotenv`, but it says

> Can I have more than production & development environment configs?
> Sadly, it's not available so far. One of the workaround is generating .env file before triggering RN's bundle script automatically using either shell script or your own custom build pipeline.

**Comment by divyanshunegi** [comment] 2019-08-21 17:24
I am getting the whole app frozen and button press does not work at all in one of the screen after using this library, need any kind of alternate, I am thinking to create a custom Native bridge anyway

**Comment by macco-chewy** [comment] 2019-08-25 19:22
@wamry: What is the current issue you're having?  I'm on react-native 0.60.3, and though it took some work to get it running, it seems to be working fine for me now.

I noticed an interesting issue pop up a couple weeks ago.  I had to `npm install` and suddenly my iOS builds stopped building with an error: 'GeneratedDotEnv.m' file not found.  Turns out the file isn't being included in the latest version.  Fortunately I had a backup of my node_modules folder.  I copied over GeneratedDotEnv.m and I was back in business.

I've forked and patched.  You can find it here.  https://github.com/macco-chewy/react-native-config/tree/fixit . Hopefully that fixes your issue.

**Comment by LuizFBrisighello** [comment] 2019-09-04 12:23
Im on RN 0.60.5 and using `react-native-config` just to be able to use env:ENVFILE=".env" and `react-native-build-config` to expose the variables to my js.. nnot the best but its working for now.

**Comment by Sathyanarayan09** [comment] 2019-09-06 08:24
Check this article for an alternative https://medium.com/commutatus/multi-environment-variable-setup-for-react-native-application-70fde4de657f

**Comment by atulmy** [comment] 2019-09-21 06:53
Considering the popularity and wide adoption, this project should be migrated to https://github.com/react-native-community

**Comment by Javi** [comment] 2019-10-15 08:02
I think this library has been effectively abandoned. Any charitative souls willing to maintain a fork?

**Comment by kelset** [comment] 2019-10-15 11:16
@atulmy I can facilitate making that happen, but the issue is that it seems that the maintainers are not responding to DMs or messages or pings in any way. If they want to reach out to me directly so that we can make this happen, pls [DM me on twitter](https://twitter.com/Kelset).

**Comment by melodydrewvr** [comment] 2019-10-16 15:35
Funny you should say that, I've opened this project:

https://github.com/x-react-native/env-config

Would dearly love some help to get it into shape so I can publish a new npm module asap!

**Comment by Gorhom** [comment] 2019-10-23 11:11
> @atulmy I can facilitate making that happen, but the issue is that it seems that the maintainers are not responding to DMs or messages or pings in any way. If they want to reach out to me directly so that we can make this happen, pls [DM me on twitter](https://twitter.com/Kelset).

any updates regarding moving this repo to `react-native-community` ?

**Comment by melodydrewvr** [comment] 2019-10-23 11:23
@Gorhom I've been in contact with @kelset about migrating my fork into react-native-community and it's all sounding very promising so far. @kelset is super busy this week though, so he's asked me to remind him about this next week when he has more time.

**Comment by Gorhom** [comment] 2019-10-23 11:45
@melodydrewvr thanks for the update 🎉

**Comment by compojoom** [comment] 2019-10-31 10:15
@melodydrewvr - any progress?
I've used this library previously on RN < 0.60 and it worked great. Just wanted to use it on a project with RN .61 and read about all the issues. 

I was thinking of forking and fixing it for us, but if this is going to move to react-native-community I would love to help with that. @melodydrewvr - if you want let's connect and sync our efforts on this.

**Comment by kelset** [comment] 2019-10-31 11:39
👋 folks - I've asked to the community owners and basically the conversation is about understanding the "overlap" between this lib and the `react-native-dotenv` alternative.

I've proposed a gradual roadmap that would lead to the two converging, as soon as I have a "final say" of some sort from their side I'll update @melodydrewvr & y'all - hopefully it won't be long.

**Comment by compojoom** [comment] 2019-10-31 19:13
The overlap between `react-native-config` and `react-native-dotenv` is only on the javascript side, right?
React-native-config on the other hand allows you to use your ENV variables both in objective-c code or in the java code. Ah, forgot gradle. So it is a little bit more powerful in my opinion.

**Comment by pedro** [comment] 2019-10-31 21:59
hey folks! so sorry we dropped the ball here – I'm no longer working at Lugg and they are super busy with other stuff, but we'd all love to work with the community to find a new home and maintainers for this project.

@melodydrewvr @kelset let us know how can we help with the move to react-native-community!

I like how `react-native-dotenv` works more smoothly in js land, whereas with this plugin you need to recompile the app to see env changes. But being able to use that env in xcode/gradle/etc is really the most important feature here. I'm sure we could make this work better with js files or even merge the two projects if there's someone interested in taking the lead.

Thanks,

**Comment by JanithaR** [comment] 2019-11-01 02:48
I am using `react-native-config` for nearly 3 years now and just a week ago got up on the fence to almost ditch it. And `react-native-dotenv` was the obvious choice but as @pedro mentioned,

> being able to use that env in xcode/gradle/etc is really the most important feature here

so it was a no brainer to say no to `react-native-dotenv` and somehow get things working and I did.

I'm using my vars in JS, Gradle, Objective-C, Java, XML and Info.plist. The only issue I haven't been able to address is that in Circle CI builds Info.plist vars are always empty so I had to address that by manually entering the needed values for particular schemes in the Info.plist file, which is not such a big deal but regardless, it would be awesome to have all configs in just one file.

No doubt this module is very powerful and it works but; most of the pain comes from the confusing documentation on Github and npmjs. Can we at least correct that first? Pretty sure there won't be as much of an outcry from the community if the documentaion is not confusing them in the first place.

**Comment by melodydrewvr** [comment] 2019-11-01 16:57
Hi everyone, I'm going to be out of contact for about a week so apologies in advance for not being able to progress the fork until I'm available again. However, if there are any pull requests you'd like to see merged please feel free to raise them in the meantime. In particular, any documentation changes that @JanithaR has mentioned would be a great starting point. I've also gone through the PRs raised against this repo that I'd like to see merged too, so hopefully when I'm free again next week we'll be in a better position to get a new package published (one way or another!)

**Comment by pedro** [comment] 2019-11-02 00:03
sounds good, yeah I haven't been following but if anyone can point me to important PR's to merge here I'll give it a try and merge/publish it - at least to stop the bleeding!

**Comment by JanithaR** [comment] 2019-11-02 01:53
It's weekend for me and I'm with my kid and wife fulltime. I'll extend my help first thing Monday.

**Comment by kelset** [comment] 2019-11-04 12:18
@pedro how about as step 0 you just migrate this repo to @melodydrewvr (of give him admin rights to the repo & the publishing ones too)?

I'll link this conversation back into the discord.

**Comment by pedro** [comment] 2019-11-05 06:18
Definitely, added!

I'll just add a mention of Lugg to the readme, but up to you guys where to take it from here 👌

**Comment by alexpchin** [comment] 2019-11-12 18:42
Hi all, do we have an ETA for this move `https://github.com/react-native-community?utf8=%E2%9C%93&q=react-native-config&type=&language=` repo?

**Comment by leethree** [comment] 2019-11-13 22:33
@pedro could you publish a new version of this library so we can use while waiting for the migration?

**Comment by kelset** [comment] 2019-11-14 10:51
👋 folks - @melodydrewvr was on holiday last week, so it will take a bit longer before this lib will get back on its feet, but a bit of patience will go a long way.

> Hi all, do we have an ETA for this move to react-native-community?

No ETA no this for the foreseeable future, if there are updates on that we will keep you updated :)

**Comment by pedro** [comment] 2019-11-14 17:27
@leethree oh doh! yes just pushed v0.12.0.

**Comment by alexpchin** [comment] 2019-11-14 17:40
Was this a published exact from this repo or did it include any PRs or changes from this master?

**Comment by alexpchin** [comment] 2019-11-14 18:24
What was included in the v0.12.0 release? There are no notes attached... Is is basically a release of the master branch of this repo, i.e. what was previously:

```
"react-native-config": "github:luggit/react-native-config#master"
```

Or were any PRs or changes included? Thanks!

**Comment by pedro** [comment] 2019-11-14 21:23
Oh yea - it was just a few things pending in master, basically just #384 !

**Comment by rnnyrk** [comment] 2019-11-14 21:46
Good to hear that it’s being picked up again! Since `react-native-dotenv` doesn’t match my requirements.

**Comment by JanithaR** [comment] 2019-11-15 02:34
Finally!
Guys, the instructions under "Availability in Build settings and Info.plist" works fine for me on my MAC but not on CircleCI. I couldn't spend as much time to figure out why. Basically things were working just fine everywhere except when writing to the InfoPlist file. My vars were always left empty. It could be common to all CI pipelines. Just a heads up.

**Comment by sarmad1995** [comment] 2019-11-24 17:38
We will really like this package to be moved to the community, this package has a good potential and functionality which others do not have, and the issues are just pilling up.

**Comment by tgearig** [comment] 2019-11-25 13:50
Even with release 0.12, I still have build errors as described in the RN 0.60.6 upgrade thread. None of the suggested workarounds have helped. There are still issues when not using the extra cocoapods script even though #349 said it should not be necessary anymore, but even using them doesn't resolve all the problems. There also appears to be at least one pull request related to fixing RN 0.60.x issues that is still open. This is a blocker for upgrading our projects, and it'd be really helpful if the migration would occur so these can get resolved.

**Comment by melodydrewvr** [comment] 2019-11-25 14:41
Hi all, apologies for the radio silence on my end. As was previously mentioned I was on holiday for a week, then work decided to go nuts for a while and then, if that wasn't enough, my house decided to start falling apart.

I'm hoping to have a bit of time to look at it this week, but until then what are the most pressing issues everyone's having? Going back through this thread it appears to be mostly documentation inaccuracies and Info.plist failing on CircleCI. I'm afraid I can't test the problems with CI builds, but does it only happen on CircleCI or is it affecting other CI services?

**Comment by JanithaR** [comment] 2019-11-25 15:14
I don't think the documentation is inaccurate anymore. Well, it would be
nice if the docs mentioned to remove GeneratedInfoPlist.h from Xcode
settings. That was required to be done on a previous version. Other than
that I think newcomers and inexperienced are in safe hands.

Better if you could fix the 0.60+ issues first. Those are huge deal
breakers.


Regards,
Janitha

**Comment by export-mike** [comment] 2019-12-17 02:17
@melodydrewvr yeah I'm getting the issues with circleci where my Info.plist keys $(NAME_OF_ENV) are not being replaced. it does work perfectly fine locally.

strange.

**Comment by export-mike** [comment] 2019-12-17 02:33
it appears the tmp.xcconfig is being populated just fine but xcode isn't reading it and passing it over to the plist file

**Comment by JanithaR** [comment] 2019-12-17 02:56
Related https://github.com/luggit/react-native-config/issues/391#issuecomment-562843897

**Comment by atulmy** [comment] 2020-01-11 20:00
@kelset, can we expect to see this package move to https://github.com/react-native-community soon? @pedro has already given a go ahead to do so in [this](https://github.com/luggit/react-native-config/issues/382#issuecomment-549679098) comment. 

May the force be strong with React Native!

<img width="195" alt="Screenshot 2020-01-12 at 1 29 52 AM" src="https://user-images.githubusercontent.com/685786/72209985-0d123280-34db-11ea-950b-c875c7f04c62.png">

**Comment by kelset** [comment] 2020-01-13 09:09
no updates on my side, there was some pushback when I asked internally 😓 I'll try to ask again

**Comment by safaiyeh** [comment] 2020-01-14 16:51
Hi @kelset someone brought this up to me. Not sure the reasoning for the push back, but I wouldn't mind helping maintain the repo when in community.

**Comment by JanithaR** [comment] 2020-01-14 17:25
That would be me. Thanks in advance on behalf of everyone using react-native-config and godspeed. :D

**Comment by kelset** [comment] 2020-01-28 12:44
Hey everyone, I tried to raise this again in the internal Discord but I'm sorry to report that - basically - until this conversation (https://github.com/react-native-community/discussions-and-proposals/issues/176) as reached a final say, there should be no expectation of this repo being moved in the RNCommunity.

What I would recommend for the time being is that the repo & npm rights are given directly to one of the new maintainers.

**Comment by compojoom** [comment] 2020-03-17 09:54
Who are the new maintainers now? @mvrdrew - I don't see a fork under your account?

**Comment by mvrdrew** [comment] 2020-03-17 10:01
I think a lot of interest in updating maintainers died out when a new npm release with the auto-linking included, as that was the biggest blocker a lot of people seemed to have.

I did make a fork under a different account with the intention of getting it into shape for RNC, but after some discussions with @kelset about whether it'd be accepted I lost a bit of momentum. The fork is here: https://github.com/x-react-native/env-config

**Comment by compojoom** [comment] 2020-03-17 10:12
@mvrdrew So what are we going to do? I haven't used the library in an year and I'm looking at it for another project. There are 37 pull requests - which doesn't really give me the confidence that it works. 

With react-native-community refusing to accept such packages it leaves us at a very unfortunate place. 

We either have to create a b-league as @kelset put it in the discussion on the react-native-community issues or just fork ourselves. I'm against forking myself and adding the pull-requests I'm interested in as this create a disconnected ecosystem. Nobody knows what is current and what not.

**Comment by kelset** [comment] 2020-03-17 11:37
just to clarify folks - I don't think that forking is the solution, but migrating this repo to another user so that it has an active maintainer with all the permissions (both github and npm).

I don't know if @pedro has the correct rights to do so since IIRC admin rights are needed.

**Comment by luancurti** [comment] 2020-03-18 20:05
@erickreutz @pedro Can you help us to migrate to another user that maintain this repo? or give the role (access to commit and publish this package) for someone to volunteer to maintain this repo (I'm one).

Who else volunteers? like this comment to @erickreutz and @pedro (or any repo owner) so they know who the volunteers are

**Comment by pedro** [comment] 2020-03-18 20:38
for sure! it's unfortunate that the move to react-native-community got stuck, but happy to give you access so we can keep things going! :+1: just gave you access.

What's your npm handle? I can give you permissions to release it too.

**Comment by luancurti** [comment] 2020-03-18 23:17
> for sure! it's unfortunate that the move to react-native-community got stuck, but happy to give you access so we can keep things going! 👍 just did it, let me know if anything.
> 
> What's your npm handle? I can give you permissions to release it too.

@pedro thanks! my npm https://www.npmjs.com/~luancurti and npm email luancurti@gmail.com

**Comment by pedro** [comment] 2020-03-19 01:16
You're the man! Really amazing how you already got to all that stuff!

I'm getting this error trying to add you to the project, any ideas?

```
$ npm owner add luancurti
npm ERR! code E405
npm ERR! 405 Method Not Allowed - PUT https://registry.npmjs.org/react-native-config/-rev/51-6193bee3061b0569f33fb50db3d00c10

$ npm -v
6.14.2
```

Can't seem to do it via the web either 🤔

**Comment by luancurti** [comment] 2020-03-19 01:22
@pedro first you need add me as a maintainer after this you can add me as a owner

follow this steps https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by pedro** [comment] 2020-03-19 01:31
Odd, from the command line it really doesn't work, but after disabling adblock I could see the admin tab and add you from the web – lemme know if it's all good now!

I'll let you decide on newer versions/etc, fwiw we were doing semver and enjoying the flexibilities of major version 0 heh. Feel free to go for 1.0 obv, whatever makes sense!

**Comment by luancurti** [comment] 2020-03-19 02:03
> Odd, from the command line it really doesn't work, but after disabling adblock I could see the admin tab and add you from the web – lemme know if it's all good now!
> 

It worked! Thanks!

> I'll let you decide on newer versions/etc, fwiw we were doing semver and enjoying the flexibilities of major version 0 heh. Feel free to go for 1.0 obv, whatever makes sense!

Of course, thanks again!

**Comment by JanithaR** [comment] 2020-03-19 03:46
Repo is back in business I see. ;)

**Comment by maxkomarychev** [comment] 2020-04-27 09:23
Hey, 

I created alternative config library [react-native-ultimate-config](https://github.com/maxkomarychev/react-native-ultimate-config). It supports all features of `react-native-config` + a bit more (like exposing typed values and not just strings).

In addition many issues that have been opened recently in react-native-config do not exist in my lib (well, at least as far as I could test them):

#449 , #446 , #438 , #432 , #426, #443, #442, #413 and others of that sort.

**Comment by luancurti** [comment] 2020-06-13 01:07
@maxkomarychev if you would like to help us to fix this issues. Will be a great help and the community will be very grateful

**Comment by lesmo** [comment] 2020-06-13 04:04
Glad to see progress here!

Seeing that things should go smoother now, @maxkomarychev if you forked from this one it'd be awesome if you pushed new features here. Many, many people are already using this lib including myself. It makes more sense to me for it to be here.

**Comment by kelset** [comment] 2020-06-15 07:33
@luancurti may be worth closing this issue, with you writing a last comment saying how the repo is now again under proper maintenance and leave some way of contacting / reaching out to you if they want to help you maintain it; then lock the issue so that it will be the last comment.

On top of that, echoing what both @luancurti and @lesmo said, @maxkomarychev I would suggest that you join forces and push your work back into this main repo and help by becoming a maintainer of it 🤗 ofc this is OSS so if you prefer to go your own way with the fork noone can blame you for that 🤗

**Comment by maxkomarychev** [comment] 2020-06-15 09:27
@luancurti @lesmo @kelset 

Hi, I created `react-native-ultimate-config` from scratch as it was much easier to avoid common issues by rethinking some design decisions. It is essentially different library. While it's important to avoid fragmentation of community contributing it back in a normal way into `react-native-config` is not something I find trivial.

That said I'd be happy to help the community. Of course I am biased to my lib but perhaps you would consider a scenario where my lib supersedes `react-native-config` in order to retain the community and get issues solved. Of course this will be a breaking change and we'd need to create migration guide. And of course this is a viable option as long as my lib is tested well and we make sure there are no degradation.

**Comment by maxkomarychev** [comment] 2020-06-15 09:36
to complement my previous answer: if superseding scenario is not an option and you prefer to keep existing ruby scripts and other things I'd still be happy to share my views on design and why I did what I did in my library

**Comment by luancurti** [comment] 2020-06-15 13:41
Thanks to all for the discussion in this issue. I'll close this because we find a new maintainer and we are looking to help to maintain this package them feel free to open pull requests in this repository

**Closed by luancurti** 2020-06-15 13:41 UTC
