### ISSUE TITLE
Missing .env file in Android Studio

### ISSUE THREAD

**Issue by compojoom** [luggit/react-native-config#327] opened 2019-01-11 13:00 UTC
This has been working for some time, but suddenly it has stopped and i'm not sure what's going on.
We have several build variants:
```
/**
 * Environment configuration
 */
project.ext.envConfigFiles = [
        debug: ".env.dev",
        staging: ".env.production",
        release: ".env.production",
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```

if we do
react-native run-android

the project builds fine - it fetched the .env.dev file and everything is fine.

However if I start Android Studio - it immediately complains that a .env file is missing. Which is correct - we don't have this file. Since sync is not able to run because of that error, we can't do anything.

If I do add a .env file, then sync runs fine. And after that I see the Build Variants and I can change them. Then I see that the correct dotenv file is being used - either .env.dev or .env.production

I dug around the dotenv.gradle file and I see that when we try to sync our project we end up here

https://github.com/luggit/react-native-config/blob/master/android/dotenv.gradle#L33

but the flavor is empty. So our configuration doesn't match the flavor and we end up with the default .env file

if I add 
project.ext.envConfigFiles = [
"":".env.dev",
        debug: ".env.dev",
        staging: ".env.production",
        release: ".env.production",
]

then android studio picks up the .env.dev file as default, but am I supposed to do this? Or is there something else going on? The docs don't mention anything about that.

**Comment by dmoss18** [comment] 2019-01-14 19:30
https://github.com/luggit/react-native-config#advanced-android-setup fixed it for me. Forgot that I needed that after I created an `applicationIdSuffix`

**Comment by aylesm** [comment] 2019-01-16 09:43
Upgrading gradle is the issue for me.  The way the react-native-config script works doesn't support getting build flavor using gradle 3.2.  I haven't found a solution for this, yet.

**Comment by compojoom** [comment] 2019-01-16 10:12
Most probably same for me.
I'm looking at this code:
```
def getCurrentFlavor() {
    Gradle gradle = getGradle()

    // match optional modules followed by the task
    // (?:.*:)* is a non-capturing group to skip any :foo:bar: if they exist
    // *[a-z]+([A-Za-z]+) will capture the flavor part of the task name onward (e.g., assembleRelease --> Release)
    def pattern = Pattern.compile("(?:.*:)*[a-z]+([A-Z][A-Za-z]+)")
    def flavor = ""

    println("gradle: ${gradle.getStartParameter().getTaskNames()}")
    gradle.getStartParameter().getTaskNames().any { name ->
        Matcher matcher = pattern.matcher(name)
        if (matcher.find()) {
            flavor = matcher.group(1).toLowerCase()
            return true
        }
    }

    return flavor
}
```

println("gradle: ${gradle.getStartParameter().getTaskNames()}") - return empty array the first time. 
If I add a .env file it goes past the first step, but after that it seems that it doesn't properly pick the 

project.ext.envConfigFiles = [
        debug: ".env.dev",
        staging: ".env.dev",
        release: ".env.production",
]

configuration.

We have the following build types 
```
buildTypes {
        debugEU {
            debuggable true
            jniDebuggable false
            renderscriptDebuggable true
            renderscriptOptimLevel 3
            minifyEnabled false
            zipAlignEnabled true
            signingConfig signingConfigs.release
            matchingFallbacks = ['debug']
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        releaseEU {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            matchingFallbacks = ['release']
        }
        staging {
            debuggable true
            jniDebuggable false
            renderscriptDebuggable true
            renderscriptOptimLevel 3
            minifyEnabled false
            zipAlignEnabled true
            signingConfig signingConfigs.release
            matchingFallbacks = ['release']
        }
    }
```

I can see them as Build Variants in android studio, but when I select staging - I see that it's reading the .env.production config instead of the .env.dev config.

**Comment by mtford90** [comment] 2019-02-18 18:06
Also seeing this on gradle v4.7.

The following seems to be ignored:

```
project.ext.envConfigFiles = [
/* ... */
]
```

And when I run e.g. `react-native run-android --variant=devDebug` I see the following error:

```
Reading env from: .env
**************************
*** Missing .env file ****
**************************
```

Is this perhaps something to do with the deprecation of `--flavor` and in favour of `--variant`?

**Comment by mtford90** [comment] 2019-02-18 18:17
Hmm so for me it turned out to be misconfiguration of `project.ext.envConfigFiles` - the keys needed to be a combination of the flavor and buildType but in *lowercase* e.g.:

```
project.ext.envConfigFiles = [
        devdebug  : ".env.development",
        devrelease  : ".env.development",
        proddebug: ".env.production",
        prodrelease: ".env.production"
]

// ...

    flavorDimensions "environment"
    productFlavors {
        dev {
            dimension "environment"
        }
        prod {
            dimension "environment"
        }
    }
    buildTypes {
        debug {
           /* ... */
        }
        release {
            /* ... */
        }
    }
```

**Comment by compojoom** [comment] 2019-02-18 19:34
ok, but we don't use productFlavors. We have just buildTypes

**Comment by SaraChicaD** [comment] 2019-05-10 17:47
The problem for me was that the installation was off, there's  PR with manual Android linking instructions, the last bit we had to add was this:

  ```
  **MainApplication.java**

   import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
  
  @Override
  protected List<ReactPackage> getPackages() {
       return Arrays.asList(
              new MainReactPackage()
           new ReactNativeConfigPackage()
      );
  }

Here's the PR for reference: https://github.com/luggit/react-native-config/pull/303/files

**Comment by tkow** [comment] 2019-08-01 08:20
I faced this when gradle task run  except for assemble (in my case running sourceSets for debug purpose). This problem is caused by what tasks are run since gradle.getStartParameter().getTaskNames() get current task name in the process. So this would extract string buildValiantSuffix  rather than flavor. This library is fragile now because this config depends on only what tasks called and doesn't support except for flavor completely matched camel case task name and original task name string must be all lowercase because the flag on pattern determined by startsWith.

As I thought it, I want to handle additional two case,  It should be fixed by flavor.endsWith instead of [startsWith](https://github.com/luggit/react-native-config/blob/master/android/dotenv.gradle#L34-L37). This should be worked in the case original task name has camel case even if flavor added task.

In another case, task name isn't added buildValiantSuffix but this task may call dotenv.gradle in the process like sourceSets. So, we need to avoid this, and maybe it is appropriate to enable switch defaultEnvFile even when project.ext.envConfigFiles exists.

So I'll pull request today if new version release coming. If I wrong something, please feel easy to tell me.

**Comment by maulikdhameliya** [comment] 2020-02-19 11:50
you need to add **defaultEnvFile** property 

check here https://stackoverflow.com/questions/49140463/missing-env-files-when-i-use-react-native-config-for-android/60299691#60299691

**Closed** 2020-03-19 01:13 UTC

**Comment by nabilfreeman** [comment] 2020-05-05 18:43
I needed to add `defaultEnvFile` too, when running `ENVFILE=xxx ./gradlew assembleRelease` the env is NOT read correctly. So I had to create an intermediate script that copies my env to a temporary location read by `defaultEnvFile`. Lame. lame. lame.

**Comment by timerg** [comment] 2020-11-05 10:55
I met this error for just have a wrong path to my env file. 
Note that the path should be relative to your project folder, not to the `build.gradle` .

Check the source code for this error: https://github.com/luggit/react-native-config/blob/63e0e0c7c0e980a5e304f6d8dc08f17d5c19527d/android/dotenv.gradle#L44

**Comment by marnusw** [comment] 2021-05-04 11:07
We define

```
project.ext.envConfigFiles = [
    debug: ".env.development",
    release: ".env.production",
]
```

and all is well when running 

```
react-native run-android --no-jetifier
```

But for some reason this error occurred when running

```
react-native run-android --no-jetifier --deviceId abcdef
```

without any other changes.

**Comment by egadstar** [comment] 2022-04-21 19:24
Should be able to just change the Run Configuration to get it to work.

<img width="647" alt="Screen Shot 2022-04-21 at 3 18 16 PM" src="https://user-images.githubusercontent.com/1434274/164537508-eec8a238-af88-4439-a0ef-af8796308dc0.png">

<img width="876" alt="Screen Shot 2022-04-21 at 3 17 21 PM" src="https://user-images.githubusercontent.com/1434274/164537566-4d95ccc3-e343-4559-8880-d61ab91778ce.png">

<img width="874" alt="Screen Shot 2022-04-21 at 3 17 26 PM" src="https://user-images.githubusercontent.com/1434274/164537581-6a1bb717-7803-4ca4-a881-7ad186a8ebe3.png">

**Comment by iledzka** [comment] 2022-12-30 12:27
> https://stackoverflow.com/questions/49140463/missing-env-files-when-i-use-react-native-config-for-android/60299691#60299691

Yes, this was my issue as well. We are using a monorepo setup and this script expects env file to be at the same directory as the core app, not at the project level..

**Comment by iledzka** [comment] 2022-12-30 12:28
> Instead of adding the `defaultEnvFile` which mentioned above, I had this error simply because of using a wrong path to my env file. Note that the path should be relative to your project folder, not to the `build.gradle` .
> 
> Check the source code for this error:
> 
> https://github.com/luggit/react-native-config/blob/63e0e0c7c0e980a5e304f6d8dc08f17d5c19527d/android/dotenv.gradle#L44

Yes, this was my issue as well. We are using a monorepo setup and this script expects env file to be at the same directory as the core app, not at the project level..

**Comment by Ajmal0197** [comment] 2024-02-05 15:37
This configurations worked for me:

```
//react-native-config
project.ext.envConfigFiles = [
        development: ".env.development",
        staging :".env.staging",
        production:'.env.production'
]
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
//react-native-config

            matchingFallbacks = ['debug', 'release'] //react-native-config


        //react-native-config
    flavorDimensions 'default'
    productFlavors {
        development {
            // dimension 'env'
            applicationIdSuffix ".testemployeeapp"
        }
        staging {
            // dimension 'env'
            applicationIdSuffix ".testemployeeapp"
        }
        production {
            // dimension 'env'
            applicationIdSuffix ".testemployeeapp"
        }
    }
        //react-native-config
```


Commands to build:
```
    "aos:DR-apk": "yarn setDevelopment &&  yarn aos:clean  && cd android && ./gradlew assembleDevelopmentRelease",
    "aos:PR-apk": "yarn setProduction &&  yarn aos:clean  && cd android && ./gradlew assembleProductionRelease",
    "aos:DD-apk": "yarn setDevelopment &&  yarn aos:clean  && cd android && ./gradlew assembleDevelopmentDebug",
    "aos:PD-apk": "yarn setProduction &&  yarn aos:clean  && cd android && ./gradlew assembleProductionDebug",
    "open-apk": "open ./android/app/build/outputs/apk/",
    "aos:dev-apk": "yarn aos:DD-apk && yarn open-apk",
    "aos:dev:release-apk": "yarn aos:DR-apk && yarn open-apk",
    "aos:prod-apk": "yarn aos:PD-apk && yarn open-apk",
    "aos:prod:release-apk": "yarn aos:PR-apk && yarn open-apk",
```

**Comment by milanvadhel-mi** [comment] 2025-01-09 13:24
> st buildTypes

Here is the [fix](https://github.com/lugg/react-native-config/issues/602#issuecomment-2580144003) for the same.
