### ISSUE TITLE
'GeneratedDotEnv.m' file not found

### ISSUE THREAD

**Issue by DLevai94** [luggit/react-native-config#187] opened 2017-11-26 14:01 UTC
If I use this package with Cocoapods and follow the README's instructions, the iOS build fails every time. With C Preprocessor error "'GeneratedDotEnv.m' file not found".

Without any pods, it works.

Does anybody have any experience with this?
I'm stuck for 2 days now because of this issue. I can't find any solution. I tried a lot of things by now.

**Comment by selfeky** [comment] 2017-12-03 20:51
@DLevai94 I have the same issue.
Did you find a solution?

**Comment by aestrro** [comment] 2017-12-04 07:30
I am running into the same issue, this error seems to be happening on react-native 0.50.+

Can the following commit be problematic for `react-native link react-native-config`?
https://github.com/facebook/react-native/commit/4c196aec902fa0b9187e11f964aed0941778a2ae

**Comment by DLevai94** [comment] 2017-12-04 13:02
@selfeky unfortunately no.

Is it possible that react-native-firebase package has the same issue? https://github.com/facebook/react-native/pull/15460#issuecomment-346295149

**Comment by DLevai94** [comment] 2017-12-04 14:02
@selfeky It works nicely if you downgrade React Native to v0.49.5!

**Comment by aestrro** [comment] 2017-12-04 17:35
Yeah, reading up on it it seems the community who uses it excitedly wanted to jump on the 50.x version of RN. Folks, this is a beautiful project - I'll write more tests on my backend while this is in flight. Great job, it has reduced plenty of my RN complications my life in many ways. I'll be patient.

**Comment by GunnarHolwerda** [comment] 2018-01-03 07:21
Hi all, I ran into this error and was using @birkir's method for resolving the issue involving CocoaPods. It was working fine util I had to archive my project where `BuildDotenvConfig.rb` would error on attempting to copy the `GeneratedDotEnv.m` and `GeneratedInfoPlistDotEnv.h` files. 

To fix this issue I updated `BuildDotenvConfig.rb` to add all lines with the comment `# ADD THIS LINE`
```ruby
#!/usr/bin/env ruby
require 'fileutils' # ADD THIS LINE
# Allow utf-8 charactor in config value
# For example, APP_NAME=中文字符
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

defaultEnvFile = ".env"

# pick a custom env file if set
if File.exists?("/tmp/envfile")
  custom_env = true
  file = File.read("/tmp/envfile").strip
else
  custom_env = false
  file = ENV["ENVFILE"] || defaultEnvFile
end

puts "Reading env from #{file}"

dotenv = begin
  # https://regex101.com/r/cbm5Tp/1
  dotenv_pattern = /^(?:export\s+|)(?<key>[[:alnum:]_]+)=((?<quote>["'])?(?<val>.*?[^\\])\k<quote>?|)$/

  # find that above node_modules/react-native-config/ios/
  path = File.join(Dir.pwd, "../../../#{file}")
  if File.exists?(path)
    raw = File.read(path)
  elsif File.exists?(file)
    raw = File.read(file)    
  else
    defaultEnvPath = File.join(Dir.pwd, "../../../#{defaultEnvFile}")
    if !File.exists?(defaultEnvPath)
      # try as absolute path
      defaultEnvPath = defaultEnvFile
    end
    defaultRaw = File.read(defaultEnvPath)
    if (defaultRaw)
      raw = defaultRaw + "\n" + raw
    end
  end

  raw.split("\n").inject({}) do |h, line|
    m = line.match(dotenv_pattern)
    next h if m.nil?
    key = m[:key]
    # Ensure string (in case of empty value) and escape any quotes present in the value.
    val = m[:val].to_s.gsub('"', '\"')
    h.merge(key => val)
  end
rescue Errno::ENOENT
  puts("**************************")
  puts("*** Missing .env file ****")
  puts("**************************")
  {} # set dotenv as an empty hash
end

# create obj file that sets DOT_ENV as a NSDictionary
dotenv_objc = dotenv.map { |k, v| %Q(@"#{k}":@"#{v}") }.join(",")
template = <<EOF
  #define DOT_ENV @{ #{dotenv_objc} };
EOF

# ensure paths exist
FileUtils.mkdir_p ENV["SYMROOT"] # ADD THIS LINE
FileUtils.mkdir_p ENV["BUILD_DIR"] # ADD THIS LINE

# write it so that ReactNativeConfig.m can return it
path = File.join(ENV["SYMROOT"], "GeneratedDotEnv.m")

File.open(path, "w") { |f| f.puts template }

# create header file with defines for the Info.plist preprocessor
info_plist_defines_objc = dotenv.map { |k, v| %Q(#define __RN_CONFIG_#{k}  #{v}) }.join("\n")

# write it so the Info.plist preprocessor can access it
path = File.join(ENV["BUILD_DIR"], "GeneratedInfoPlistDotEnv.h")
File.open(path, "w") { |f| f.puts info_plist_defines_objc }

if custom_env
  File.delete("/tmp/envfile")
end

puts "Wrote to #{path}"
```

This ensured the full file paths I was attempting to write to existed before writing.

**Comment by birkir** [comment] 2018-01-19 19:35
Yes I ran into this as well at some point on a new project that didn't have any previously archived builds, I updated the shell script snippet.

**Comment by TimothePearce** [comment] 2018-01-29 19:56
Hi guys, is this the only solution right now to use `react-native-config` with cocoapods?

**Comment by ifero** [comment] 2018-02-02 10:56
Yes, at the moment the only solutions available are @birkir or mine (https://github.com/luggit/react-native-config/issues/83#issuecomment-349974826), but @birkir 's is much more cleaner and work inside Xcode.
The only think that I don't like is that I had to create 3 build-env.sh files, one for each target (prod, stage, dev)

**Comment by alextorn** [comment] 2018-02-07 08:22
Folks, you should double check if libReactNativeConfig.a is available in target settings - Build Phases - Link Binary With Libraries:

<img width="903" alt="screenshot 2018-02-06 17 12 11" src="https://user-images.githubusercontent.com/6455482/35905536-96a8d386-0bf8-11e8-9c02-f36c29ef036f.png">

Sometimes regular automatic linking is not enough. I solved the problem by [manual linking](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) react-native-config library. 

react-native: v 0.52.2
react-native-config: v 0.11.5

**Comment by dancomanlive** [comment] 2018-02-16 06:07
@alextorn  libReactNativeConfig.a is missing indeed. Would you be so kind to elaborate on the manual linking? The RN docs are not very clear. Thanks!

**Comment by apparition47** [comment] 2018-02-27 07:09
After spending half a day on this, managed to get get this project to build and expose the .env in JS but _without_ CocoaPods. Instead, I [manually linked this project as which I documented in my updated README](https://github.com/Clintal/react-native-config/tree/ios-manual-linking#manual-linking-ios).

Using RN 0.53.0.

Basically the process is to:
1. add the `../node_modules/react-native-config/ios/ReactNativeConfig.xcodeproj` to your own project
2. In your Target settings, Build Phases, Link Binary With Libraries, add `libReactNativeConfig.a.`
3. Manage scheme, expand "Build", click "Pre-actions", "New Run Script Action", enter:
```bash
if [ "${ENVFILE}" ]; then echo "${ENVFILE}" > /tmp/envfile ; else echo ".env" > /tmp/envfile; fi
```
4. Ensure your `.env.prod` file has some key/values without spaces around the `=` like I've been seeing around these threads. Then run in term: `$ ENVFILE=.env.prod react-native run-ios`.

**Comment by benjaminketron** [comment] 2018-03-21 06:50
@apparition47 Thank you. This saved a bit of time. In practice i found step three to be unnecessary when importing with

`#import <ReactNativeConfig/ReactNativeConfig.h>`

rather than

`#import "ReactNativeConfig.h"`

Does that make sense or did I miss something in the thread you were targeting with step 3?

**Comment by PatNeedham** [comment] 2018-04-26 19:33
@birkir I tried following your suggestion with the ./scripts/build-env.sh file and adding it to the new `build-env` target, but when attempting to build or clean the app from Xcode, I always get `Shell Script Invocation Error`:

```
make: *** No targets specified and no makefile found.  Stop.
Command /usr/bin/make failed with exit code 2
```

Same result even after changing the permissions for that shell script. Did you are anyone else run into this script invocation issue as well, and if so how was it resolved?

**Comment by TimothePearce** [comment] 2018-04-26 20:44
@PatNeedham It works for me, I remember I got your mistake when I positioned the target after React in the build order.

Try in that order : 
<img width="659" alt="capture d ecran 2018-04-26 a 22 41 28" src="https://user-images.githubusercontent.com/11693661/39330900-4c7680e0-49a3-11e8-8306-b93377ecdbd8.png">


I hope it helps you.

**Comment by PatNeedham** [comment] 2018-04-26 21:16
@TimothePearce my targets were also in that order. When I clicked on the `Manage Schemes...` button in the lower left of that pop-up, I noticed `build-env` did not initially have `Shared` checked on the right hand column:

![image](https://user-images.githubusercontent.com/967811/39332013-3c7fc7ac-4974-11e8-9752-6518008b88c1.png)

Having that checked still produced the same shell script invocation result.

Running `ls -l scripts/build-env.sh` from command line results in
```
---------x  1 patneedham  staff  553 Apr 26 15:16 scripts/build-env.sh
```

Actually made some changes to eliminate those permission restrictions so it is now like this:
```
-rwxrwxrwx  1 patneedham  staff  553 Apr 26 17:12 scripts/build-env.sh
```

Same result when trying to run Xcode build. Do those updated permissions look off somehow?

**Comment by TimothePearce** [comment] 2018-04-26 21:50
@PatNeedham You must click on `Edit Scheme...` not `Manage Schemes...` to edit the build order.
You are not suppose to have any `build-end` target in the screenshot you send.

Look at mine: 
<img width="773" alt="capture d ecran 2018-04-26 a 23 49 38" src="https://user-images.githubusercontent.com/11693661/39333800-84a3930a-49ac-11e8-8cfb-fe377ffbe0d6.png">

**Comment by peacechen** [comment] 2018-05-10 19:15
The generated files are a nightmare after upgrading to React Native 0.55.   *birkir*'s script does the job of generating the DotEnv files, but using it with a new target isn't able to handle different schemes.

To support different schemes, use his script without setting `TARGET_ENV` and place it in the scheme's `Build` -> `Pre-action` script box.
```
echo ".env.prod" > /tmp/envfile
./ios/react-native-config-gen.sh
```


And here's the modified `react-native-config-gen.sh` script:
```
#/bin/sh

RNCDIR="./node_modules/react-native-config/ios"

if [ ! -z "$SYMROOT" ]; then
  # Ensure directories exist before copying files
  mkdir -p $SYMROOT
  mkdir -p $BUILD_DIR

  # Build dotenv
  cd $RNCDIR
  ./ReactNativeConfig/BuildDotenvConfig.ruby
  cd -

  # Copy generated dotenv files to node_modules directory
  cp "$BUILD_DIR/GeneratedInfoPlistDotEnv.h" "$RNCDIR/ReactNativeConfig/GeneratedInfoPlistDotEnv.h"
  cp "$SYMROOT/GeneratedDotEnv.m" "$RNCDIR/ReactNativeConfig/GeneratedDotEnv.m"
fi
```

**Comment by vasilich6107** [comment] 2018-05-19 20:11
Hi)
I had a similar issue. When passed through the README installation instructions everything is ok.
But after using command `pod install` I got similar error ``

If you are experiencing similar problems add this lines to the end of your `podfile`

`
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-config"
      target.remove_from_project
    end
  end
end
`

**Comment by pontusab** [comment] 2018-06-07 15:43
@vasilich6107's Solution work, but don't be stupid like me and forget to remove the pod `pod 'react-native-config', :path => '../node_modules/react-native-config'`

**Comment by mjgallag** [comment] 2018-06-17 17:22
FYI, this appears to be the same issue as #125.

**Comment by Dictory** [comment] 2018-07-09 11:37
If you use `fastlane` try `bundle exec fastlane comand`

**Comment by reilem** [comment] 2018-08-19 12:58
@vasilich6107 & @pontusab 's solution worked for me. Dragged an dropped the ReactNativeConfig.xcodeproj from node_modules to the 'Libraries' folder and added "libReactNativeConfig.a" (NOT libreact-native-config.a) under 'Link Binary With Libraries' in 'Build Phases'. And removing the left over reference in Podfile from the automatic linking.

Then using `#import <ReactNativeConfig/ReactNativeConfig.h>` to import instead of `"ReactNativeConfig.h"`.

**Comment by Martian2Lee** [comment] 2018-08-21 11:34
Thank you @scottmas , saved my day!

**Comment by gatspy** [comment] 2018-09-17 12:50
@birkir perfect solution, thank you!
[issuecomment-353156419](https://github.com/luggit/react-native-config/issues/187#issuecomment-353156419)

**Comment by jpmazza** [comment] 2019-01-10 18:58
Hey!
I'm having this issue, too.
1_ I've set as Info.plist Preprocessor Prefix File: `${BUILD_DIR}/GeneratedInfoPlistDotEnv.h`.
2_ I have the react-native-config manually linking.
3_ I have three different env files: `.env.dev, .env.beta, .env.prod`

I don't even find the GeneratedDotEnv.m file and GeneratedInfoPlistDotEnv neither. Where should be them located?

Any thoughts? Thanks in advance!

**Comment by smakosh** [comment] 2019-02-27 00:41
I followed your solution @birkir but now I'm getting this error

```
he following build commands failed:

	ExternalBuildToolExecution build-env
(1 failure)
```

**Comment by birkir** [comment] 2019-03-01 16:41
@smakosh  Go to the log explorer panel, select all (log, warnings and errors) and scroll up until you find the reason.

What you pasted is not why it failed, just that it failed and we can't help you with only this information I am afraid.

**Comment by smakosh** [comment] 2019-03-01 16:46
I solved it by adding this post_install script to my podfile

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
                           " && RNC_ROOT=./node_modules/react-native-config/"\
                           " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      target.build_phases << phase
      target.build_phases.move(phase,0)
    end
  end
end
```

**Comment by vlad-fylp** [comment] 2019-04-14 14:39
A combination of @smakosh's reply and this: https://github.com/luggit/react-native-config/issues/125#issuecomment-436872749
helped

**Comment by maxkomarychev** [comment] 2019-05-17 00:19
hey!
please check out my pr: #349 it introduces new way of integration with ios project where you don't need to tweak various things in your podfile, also overall integration flow is smaller

thanks.

**Comment by nethergrim** [comment] 2019-05-24 20:42
Is there anything I can do with this error?

`ld: warning: directory not found for option '-L/Users/andrii/Library/Developer/Xcode/DerivedData/theftpatrol-apjuziaodvnhqxcakkzaaxjydwis/Build/Products/Prestige debug-iphonesimulator/React'
ld: warning: directory not found for option '-L/Users/andrii/Library/Developer/Xcode/DerivedData/theftpatrol-apjuziaodvnhqxcakkzaaxjydwis/Build/Products/Prestige debug-iphonesimulator/yoga'
ld: library not found for -lReact
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by digitaldavenyc** [comment] 2019-05-30 23:02
> Hi)
> I had a similar issue. When passed through the README installation instructions everything is ok.
> But after using command `pod install` I got the same error `'GeneratedDotEnv.m' file not found`
> 
> If you are experiencing similar problems add this lines to the end of your `podfile`
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     if target.name == "react-native-config"
>       target.remove_from_project
>     end
>   end
> end
> ```

This worked for me

**Comment by ekowcharles** [comment] 2019-07-23 06:12
@birkir Thanks for the solution.

A quick note, running the solution as is results in the following error: `Xcode 10.2: Unable to spawn process (Exec format error)`

I had to change the first line in the *.sh script from `#bin/sh` to `#!/bin/sh`. Minor fix but huge gain.

**Comment by salvariable** [comment] 2019-07-23 22:31
I'm having this error on RN 0.60... not sure how to try manual link since 0.60 introduces autolinking.

'react-native link react-native-config' doesn't work.

Any idea of what can be done?

**Comment by jesusemendoza** [comment] 2019-07-25 01:26
@salvariable I'm on version 0.60.3 and Instead of using:
`react-react-native link react-native-config`
you can manually add:
`pod 'react-native-config', :path => '../node_modules/react-native-config'`
to your `ios/Podfile` but before you do a pod install I did what @smakosh suggested and added
to the bottom  of the `Podfile`
```
post_install do |installer|
    installer.pods_project.targets.each do |target|

      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"

      targets_to_ignore = %w(React yoga)

      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

      if target.name == 'react-native-config'
        phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
        phase.shell_script = "cd ../../"\
                             " && RNC_ROOT=./node_modules/react-native-config/"\
                             " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                             " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
                             " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
  
        target.build_phases << phase
        target.build_phases.move(phase,0)
      end

    end
  end
```

Then do a `pod install`. Hope that works for you.

**Comment by deepshikha139** [comment] 2019-07-25 12:56
I tried to run pod install, and everything is working fine.

**Comment by salvariable** [comment] 2019-07-25 15:19
Thank you @jesusemendoza! I'm still having trouble with the new way of installing / linking

**Comment by rnnyrk** [comment] 2019-08-01 12:26
@scottmas solution worked for my. To clarify the steps: Removed the package from my Podfile and manually linked it by dragging `/node_modules/react-native-config/ios/ReactNativeConfig.xcodeproj` to my Libraries in Xcode and linked the package `libReactNativeConfig.a` under Build Phases > Link Binary with Libraries.

**Comment by argarner** [comment] 2019-08-02 09:39
After running the complete README install with `react-react-native link react-native-config`,  I confirmed `pod 'react-native-config', :path => '../node_modules/react-native-config'` was in my podfile but it still didn't work. Adding the `post_install do |installer|...` block to the end of the file as per @jesusemendoza fixed it. Thank you Jesus!

**Comment by digitaldavenyc** [comment] 2019-08-04 17:23
We've decided to move on from this repo, the amount of issues just installing is really crazy... for those that have had enough of the pain and suffering, [react-native-dotenv](https://github.com/zetachang/react-native-dotenv) is very simple to install and works well

**Comment by argarner** [comment] 2019-08-05 00:31
> We've decided to move on from this repo, the amount of issues just installing is really crazy... for those that have had enough of the pain and suffering, [react-native-dotenv](https://github.com/zetachang/react-native-dotenv) is very simple to install and works well
@digitaldavenyc does react-native-dotenv provide access to .env files within ios/android native code, like this package does?

**Comment by smakosh** [comment] 2019-08-05 08:05
@argarner nope

**Comment by helderburato** [comment] 2019-09-06 23:56
I'm on version `0.60.5` of React Native.

I made the following steps:

1. `yarn add react-native-config`;

2. `react-native link react-native-config`

3. Add this code at the end of your PodFile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
                            " && RNC_ROOT=./node_modules/react-native-config/"\
                            " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                            " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
                            " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      target.build_phases << phase
      target.build_phases.move(phase,0)
    end

  end
end
```

4. `cd ios && pod deintegrate && pod install`

This works fine for me. :)

**Comment by MaffooBristol** [comment] 2019-09-28 14:26
The latest solution worked for me too, but I don't really know why it needed to 😕 

It used to build fine but then I added react-native-navigation and it exploded!

**Comment by rptoma** [comment] 2019-10-02 22:10
@MaffooBristol exactly my experience

**Comment by jasonbodily** [comment] 2019-10-08 18:40
@helderburato 's answer works for me too, but since I'm using react-native 0.60+, my build now complains that it's linked. When I run `react-native unlink react-native-config`, it works and there's no complaining.

**Comment by MaffooBristol** [comment] 2019-10-09 09:25
For the time being I've actually removed this module as it keeps springing up random errors and the original solution I used seems very unstable. So my advice is that although that podfile hack does work initially, it may not be worth the additional problems it causes.

Not sure what other solution there is right now though unfortunately :(

**Comment by M1chaelChen** [comment] 2019-10-23 20:48
Thanks to my colleague who found this magical commit which works perfectly. No workaround needed!
`yarn add react-native-config@luggit/react-native-config#1eb6ac01991210ddad2989857359a0f6ee35d734`

"react-native": "0.61.2"

**Comment by GaniduAsh** [comment] 2019-10-31 05:22
This relates with a permission issue , executing will  sudo chmod -R 777  /path  of the source will solve the issue :)

**Comment by zedtux** [comment] 2019-11-08 09:59
I had to adapt the post install script to make it working (and also to make it more Ruby style):

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    next unless target.name == 'react-native-config'

    phase = target.project.new(
      Xcodeproj::Project::Object::PBXShellScriptBuildPhase
    )
    phase.shell_script = <<-SCRIPT
      cd ../../ && \
      RNC_ROOT=./node_modules/react-native-config/ && \
      export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig && \
      export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig && \
      ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb ${SRCROOT} ${SRCROOT}
    SCRIPT

    target.build_phases << phase
    target.build_phases.move(phase, 0)
  end
end
```

Adding the two `${SRCROOT}` in order to define the place where is the `.env` file and where to build the `GeneratedDotEnv.m` file fixed the script.

**Comment by pedro** [comment] 2019-11-14 21:26
:+1: #349 has been merged/released with `0.12`

**Closed by pedro** 2019-11-14 21:26 UTC

**Comment by MaxInMoon** [comment] 2019-11-26 13:31
@pedro can you have a look on https://github.com/luggit/react-native-config/issues/414 please?
I can't make it work with rn 0.61 and 0.12

**Comment by vvusts** [comment] 2019-11-27 08:06
@zedtux I get error that .ruby file doesn’t exist. I have file on this path but it ends with .rb any idea?

**Comment by zedtux** [comment] 2019-11-27 08:21
@vvusts well then just replace `.ruby` by `.rb` 😉

**Comment by leemcmullen** [comment] 2020-04-02 10:59
I was experiencing this issue when trying to build on AppCenter with RN0.61 and react-native-config 0.12. 

I was using the helpful script posted by @zedtux (https://github.com/luggit/react-native-config/issues/187#issuecomment-551493446) to get around it.

I'm now running RN0.61.5, I've upgraded to react-native-config 1.0 and AppCenter now builds without a problem.

**Comment by LaVielle** [comment] 2021-08-17 08:22
I recently ran into this issue. Simply updating `react-native-config` from 1.4.2 to 1.4.3 fixed the issue for me!

**Comment by chenop** [comment] 2022-09-19 06:13
Clean xcode and rebuilding fixed it for me

**Comment by anija** [comment] 2022-10-20 12:38
Experiencing this occasionally on 1.4.11

**Comment by spsaucier** [comment] 2022-10-28 14:30
We fixed by removing the requirements for `GeneratedInfoPlistDotEnv.h`, since it's not recommended by the `react-native-config` Readme anymore, and then we followed the instructions towards Config.xcconfig enabling env vars in Info.plist: https://github.com/luggit/react-native-config#availability-in-build-settings-and-infoplist, making sure that our Info.plist was using the proper `$(VAR)` syntax.

**Comment by dcsan** [comment] 2022-12-07 13:42
@chenop what do you mean by `clean xcode` ? I have a `clean-all` task as follows, are there any other ghostly artifacts that need to be hunted down?

```
clean-all:
    -rm ./package-lock.json
    -rm -rf ./node_modules
    -rm -rf ./ios/Pods
    -rm -rf ./ios/Podfile.lock
    -rm -fr $TMPDIR/metro-cache
    -rm $TMPDIR/haste-map-*
```

**Comment by chenop** [comment] 2022-12-07 15:23
@dcsan clean xcode means: 
Product --> Clean Build Folder

**Comment by ShepSims** [comment] 2023-01-23 22:05
> @dcsan clean xcode means: Product --> Clean Build Folder

Useful Hotkey for this is (Shift + Command + K) in XCode

**Comment by ko-devHong** [comment] 2023-02-24 02:09
This problem appears to be caused by the failure to find the `.env` configuration file. I put the `.env` file in the project and did the following action. 

1. xcode -> app icon lick => edit scheme click
![스크린샷 2023-02-24 오전 11 07 40](https://user-images.githubusercontent.com/45538347/221074462-452004b8-2126-4ea1-a49c-7c0125d115eb.png)
2. build => pre-actions 
3. write scripts

example 
```shell
# Type a script or drag a script file from your workspace to insert its path.
PROD_FILE="${PROJECT_DIR}/../.env.production"
DEV_FILE="${PROJECT_DIR}/../.env.development"
if [ -f "$PROD_FILE" ]; then
    cp "$PROD_FILE" "${PROJECT_DIR}/../.env"
else 
    cp "$DEV_FILE" "${PROJECT_DIR}/../.env"
fi

"${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"
```

**Comment by ShepSims** [comment] 2023-03-09 20:10
I had accidentally deleted my tmp.xcconfig from the ios folder 

a quick 
cd ios && pod install && cd .. from the project root directory worked for me as that regenerates the file 

might also clean XCode before running again (⌘Command + K )

**Comment by brascene** [comment] 2023-04-06 10:31
Pod install again and error was gone.
