### ISSUE TITLE
Availability in Build settings and Info.plist problem

### ISSUE THREAD

**Issue by majidln** [luggit/react-native-config#391] opened 2019-09-24 07:21 UTC
where we must to add below code in step 6 of ```Availability in Build settings and Info.plist``` section:

```"${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"```

**Comment by JanithaR** [comment] 2019-10-25 05:14
In your scheme settings, Build -> Pre-actions
If you haven't followed [this](https://github.com/luggit/react-native-config#ios-multi-scheme) approach then follow these steps first and then add the line you have quoted above,

> Expand the "Build" settings on left
> Click "Pre-actions", and under the plus sign select "New Run Script Action"

**Comment by rafaelmaeuer** [comment] 2019-12-07 11:42
Since the update from 0.11.7 to 0.12.0 all variables used in info.plist are only updated on the second build. The Build log shows RN-config updates the variables correct on first build, but the info.plist in the produced app is not updated correspondingly. 

This was better in v0.11.7 when plist-preprocessing was possible using the `GeneratedInfoPlistDotEnv.h` file. As this file is not longer produced after the update (due to changes in `BuildDotenvConfig.ruby` now `BuildDotenvConfig.rb`) this convenient way of updating variables on first build is no longer available.

Any thoughs on this?

**Comment by JanithaR** [comment] 2019-12-10 13:25
Looks like @rafaelmaeuer 's comment and #409 are related.

**Comment by export-mike** [comment] 2019-12-17 03:56
why was the code generating, GeneratedInfoPlistDotEnv.h removed?

**Comment by JanithaR** [comment] 2019-12-17 04:22
> GeneratedInfoPlistDotEnv.h removed?

Yep

> why was the code generating,

I don't really understand the context to give an answer to this.

**Comment by export-mike** [comment] 2019-12-17 22:39
Yeah so on my circle ci build, I'm now running this custom script which is a temporary measure. 

patches in the .env file into info.plist

```js
#!/usr/bin/env node
const fs = require('fs');
const dotenv = require('dotenv');
const promisify = require('util').promisify;
const writeFile = promisify(fs.writeFile);
const readFile = promisify(fs.readFile);

async function main() {
  try {
    console.log('===================== THIS IS A TEMPORARY SCRIPT ===================');
    console.log('===================== UPDATING Info.plist with .env ================');
    console.log('====================================================================');
    console.log('see Issue: https://github.com/luggit/react-native-config/issues/391');

    const envfile = await readFile('./.env', 'utf-8');
    const plist = await readFile('./ios/medapp/Info.plist', 'utf-8');
    const env = dotenv.parse(Buffer.from(envfile));
    let plistupdated = plist;
    Object.entries(env).forEach(([key,value]) => {
      plistupdated = plistupdated.replace(new RegExp(`\\$\\(${key}\\)`, 'g'), value);
    });
    await writeFile('./ios/medapp/Info.plist', plistupdated, 'utf-8');
    await writeFile('./ios/medapp/Info.plist.bak', plist, 'utf-8');
  } catch (e) {
    console.error(e);
    console.error(`Unable to read .env file`);
    process.exit(1);
  }
}
main();

```

**Comment by dunghuynh** [comment] 2019-12-20 05:41
My temporarity word around is to remove the app and build again:
```
ENVFILE=.env.test node_modules/.bin/detox build --configuration ios.sim.release
rm -rf ios/build/Build/Products/Release-iphonesimulator/Remitano.app
ENVFILE=.env.test node_modules/.bin/detox build --configuration ios.sim.release
ENVFILE=.env.test node_modules/.bin/detox test --configuration ios.sim.release
```

**Comment by luis-f-lins** [comment] 2020-01-07 13:02
@export-mike Your custom script worked for me, thank you. I hope they a proper fix is released soon.

**Comment by tpucci** [comment] 2020-01-08 08:45
Hi ! If your issue is `Build input file cannot be found: GeneratedDotEnv.m` and if you are using pods and RN > 0.60, you can patch the podspec with this commit : https://github.com/bamlab/react-native-config/commit/05761868680ad46c9dbd1f56d7d504f056f444db

```diff
  s.script_phase = {
    name: 'Config codegen',
    script: %(
- set -ex
- HOST_PATH="$SRCROOT/../.."
- "${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig/BuildDotenvConfig.rb" "$HOST_PATH" "${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig"
- ),
+      set -ex
+      HOST_PATH="$SRCROOT/../.."
+      ${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig/BuildDotenvConfig.rb $HOST_PATH ${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig
+    ),
    execution_position: :before_compile,
-    input_files: ['$(SRCROOT)/ReactNativeConfig/BuildDotenvConfig.rb']
+    input_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb'],
+    output_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/GeneratedDotEnv.m']
  }

  s.source_files = 'ios/**/*.{h,m}'
```

*Explanation:* The custom pod script generates the `GeneratedDotEnv.m` file at the same time XCode requires it. There is a race condition. In order to fix that, we need to tell XCode that our script outputs one file that is required in another step. Doing so, XCode new Build system will create a correct dependency graph and erase this race condition.

*Source:* http://www.gietal.net/blog/xcode10-and-prebuild-script-output-files-xcfilelist

**Comment by grit96** [comment] 2020-03-18 16:51
@rafaelmaeuer did you end up using a workaround that worked? Currently my workaround is to build the first env of the app twice.

**Comment by rafaelmaeuer** [comment] 2020-03-23 14:59
I didn't had the time to test any workaround yet, so I am doing the same: building the app twice is annoying but it works...

**Comment by leemcmullen** [comment] 2020-04-17 14:55
@tpucci Thanks for your suggestion (https://github.com/luggit/react-native-config/issues/391#issuecomment-571948199), it's the only thing which seems to work for me, only issue is remembering to edit the podspec if/when node_modules is rebuilt 😩

**Comment by tpucci** [comment] 2020-04-17 15:18
> @tpucci Thanks for your suggestion ([#391 (comment)](https://github.com/luggit/react-native-config/issues/391#issuecomment-571948199)), it's the only thing which seems to work for me, only issue is remembering to edit the podspec if/when node_modules is rebuilt

@leemcmullen I recommend that you use 'patch-package' in order not to worry about that.

**Comment by leemcmullen** [comment] 2020-04-17 15:22
@tpucci Good idea, thanks Thomas! 👍

**Comment by export-mike** [comment] 2020-04-18 14:34
anyplans to release this patch as a fix?

**Comment by jacobcabantomski-ct** [comment] 2020-05-13 16:35
If anyone needs https://github.com/luggit/react-native-config/issues/391#issuecomment-571948199 as a permanent patch:

1. Add [patch-package](https://github.com/ds300/patch-package)
```bash
yarn add --dev patch-package # or npm install -D patch-package
```

2. Add `patch-package` to `postinstall` step in `package.json`
```json
...
  "scripts": {
    ...
    "postinstall": "patch-package",
    ...
    },
...
```
In our script we also need [react-native-inhibit-warnings](https://github.com/mattijsf/react-native-inhibit-warnings) and [jetifier](https://github.com/mikehardy/jetifier)
```json
"postinstall": "react-native-inhibit-warnings && jetifier && patch-package",
```
3. Create the patchfile at `patches/react-native-config+1.0.0.patch`
```
diff --git a/node_modules/react-native-config/react-native-config.podspec b/node_modules/react-native-config/react-native-config.podspec
index 918eb47..e0dfec7 100644
--- a/node_modules/react-native-config/react-native-config.podspec
+++ b/node_modules/react-native-config/react-native-config.podspec
@@ -25,7 +25,8 @@ HOST_PATH="$SRCROOT/../.."
 "${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig/BuildDotenvConfig.rb" "$HOST_PATH" "${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig"
 ),
     execution_position: :before_compile,
-    input_files: ['$(SRCROOT)/ReactNativeConfig/BuildDotenvConfig.rb']
+    input_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb'],
+    output_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/GeneratedDotEnv.m']
   }

   s.source_files = 'ios/**/*.{h,m}'
```
(Note I removed whitespace changes from @tpucci 's patch)
4. `yarn` or `npm install`
5. `cd ios && pod install --repo-update && cd -`

Confirmed working on:

`react-native`: `0.61.5`
`react-native-config`: `1.0.0`

**Comment by socialcode-rob1** [comment] 2020-05-19 16:44
@jacobcabantomski-ct any reason why this needs to stay as a match and not merged, I've seen others fork the project just to make this change

**Comment by jacobcabantomski-ct** [comment] 2020-05-19 17:08
@socialcode-rob1 https://github.com/luggit/react-native-config/pull/454

**Closed** 2020-05-19 17:37 UTC

**Comment by rafaelmaeuer** [comment] 2020-05-21 20:36
Thanks for adding the patch to the latest release, but the plist population on first build is still not working for me. Can someone post a working example on how to configure this correctly?

**Comment by grit96** [comment] 2020-06-01 12:19
@rafaelmaeuer Can your steps be added to the README, or should a more automatic solution be investigated?

**Comment by rafaelmaeuer** [comment] 2020-06-02 09:10
If this is wanted I can update the readme to include my solution. @luancurti what do you think?

**Comment by ThanhNghia944** [comment] 2020-06-12 17:40
working on:   "react-native-config": "1.2.1",

**Comment by luancurti** [comment] 2020-06-13 01:01
> If this is wanted I can update the readme to include my solution. @luancurti what do you think?

I think it's a good idea to add this `throubleshoting` in the README @rafaelmaeuer feel free to make this PR

**Comment by HinHin86197** [comment] 2020-08-17 15:39
This is my solution
- Create a variable on config.xcconfig file (ex: APP_NAME_TEST = AppNameTest)
- Call it on info.plist : ${APP_NAME_TEST} --> Build
- Try with another variable on your env file(staging, production...) --> Rebuild
- Enjoy !!!
---> Hope to help you.

**Comment by yksingh12** [comment] 2020-08-19 07:01
> Hi ! If your issue is `Build input file cannot be found: GeneratedDotEnv.m` and if you are using pods and RN > 0.60, you can patch the podspec with this commit : [bamlab@0576186](https://github.com/bamlab/react-native-config/commit/05761868680ad46c9dbd1f56d7d504f056f444db)
> 
> (file located at `node_modules/react-native-config/react-native-config.podspec`)
> 
> ```diff
>   s.script_phase = {
>     name: 'Config codegen',
>     script: %(
> - set -ex
> - HOST_PATH="$SRCROOT/../.."
> - "${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig/BuildDotenvConfig.rb" "$HOST_PATH" "${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig"
> - ),
> +      set -ex
> +      HOST_PATH="$SRCROOT/../.."
> +      ${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig/BuildDotenvConfig.rb $HOST_PATH ${PODS_TARGET_SRCROOT}/ios/ReactNativeConfig
> +    ),
>     execution_position: :before_compile,
> -    input_files: ['$(SRCROOT)/ReactNativeConfig/BuildDotenvConfig.rb']
> +    input_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb'],
> +    output_files: ['$PODS_TARGET_SRCROOT/ios/ReactNativeConfig/GeneratedDotEnv.m']
>   }
> 
>   s.source_files = 'ios/**/*.{h,m}'
> ```
> 
> _Explanation:_ The custom pod script generates the `GeneratedDotEnv.m` file at the same time XCode requires it. There is a race condition. In order to fix that, we need to tell XCode that our script outputs one file that is required in another step. Doing so, XCode new Build system will create a correct dependency graph and erase this race condition.
> 
> _Source:_ http://www.gietal.net/blog/xcode10-and-prebuild-script-output-files-xcfilelist

Worked for me.

**Comment by Voltron369** [comment] 2020-09-10 13:16
I'm using pod generated xcconfig files, so I created a post_install that appends #include? "tmp.xcconfig"

```
post_install do |installer|
  puts "Updating Targets to include react-native-config env variables"
  installer.generated_aggregate_targets.each do |target|
    ["Debug", "Release"].each do |config|
      rpath = target.xcconfig_relative_path(config)
      puts "    updating #{target.name} :#{config}"
      open(rpath, 'a') { |f|
          f.puts "#include? \"tmp.xcconfig\""
      }
    end
  end
end

```

**Comment by abdeali41** [comment] 2020-09-30 14:45
I was having the same issue but I found that my bash script was not properly written in the prebuild scripts. It should be like 
`cp ${PROJECT_DIR}/../.env.dev ${PROJECT_DIR}/../.env
# replace .env.dev for your file
"${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"
`
also, you have to write in the input shell -> /bin/sh
and in Provide build settings from  -> "your target"

**Comment by devoto13** [comment] 2020-10-05 19:48
It was not very clear from [README instructions](https://github.com/luggit/react-native-config#availability-in-build-settings-and-infoplist) where to add the script to generate `tmp.xcconfig`, so I mistakenly added it to the Build Phases under my application target. As it turned out it was too late: `Info.plist` is copied to the BUILD_DIR as a first step of the build and `tmp.xcconfig` is generated after that. As a result on the first build values from the `tmp.xcconfig` are not picked up and changes to the `.env` file are only picked up by the second build after the change is made.

The correct place where to add `BuildXCConfig.rb` is in Edit scheme... -> Build -> Pre-actions. Also make sure to select your target for "Provide build settings from". 

<img width="896" alt="image" src="https://user-images.githubusercontent.com/823594/95124673-0fe14180-0754-11eb-85f3-7cfffe94c493.png">

Otherwise the approach seems to work correctly and you don't need to make loads of manual work as described in https://github.com/luggit/react-native-config/issues/391#issuecomment-632331803.

PS Note that variables don't have `RNC_` prefix as with the legacy approach involving the `Info.plist` preprocessing.

**Comment by ledek89** [comment] 2020-10-14 10:33
> PS Note that variables don't have `RNC_` prefix as with the legacy approach involving the `Info.plist` preprocessing.

Ty bro! That was my issue

**Comment by arcollector** [comment] 2020-10-21 20:32
This is my solution

This is my pre action build script, I use `/tmp/envfile` where I copy my current env file based on User-defined variable `${RNCONFIG_ENVIRONMENT}`
```bash
# Type a script or drag a script file from your workspace to insert its path.
# exec > ${PROJECT_DIR}/prebuil#d.log 2>&1
cp "${SRCROOT}/../.env.${RNCONFIG_ENVIRONMENT}" "/tmp/envfile"
"${SRCROOT}/../node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb" "${SRCROOT}/.." "${SRCROOT}/tmp.xcconfig"
```

To setup a user defined variable, do this,
Xcode -> Left panel (select top root project) -> Targets (your project) -> Build settings -> (click) Plus icon -> Add user defined settings

![Screen Shot 2020-10-21 at 17 19 57](https://user-images.githubusercontent.com/1631140/96778565-3fce4d00-13c2-11eb-8211-2982ea6fc989.png)

Add a variable called `RNCONFIG_ENVIRONMENT` with both values, for debug and release

![Screen Shot 2020-10-21 at 17 25 15](https://user-images.githubusercontent.com/1631140/96778694-67251a00-13c2-11eb-86be-e8ab29faf670.png)

**Remember to create both env in your root react native project, as .env.development and .env.production**

The final changed to modified the file `node_modules/react-native-config/ios/ReactNativeConfig/ReadDotEnv.rb`

```ruby
diff --git a/old.txt b/new.txt
index fe4b77b..7e89b79 100644
--- a/old.txt
+++ b/new.txt
@@ -14,28 +14,30 @@ def read_dot_env(envs_root)
   # pick a custom env file if set
   if File.exist?('/tmp/envfile')
     custom_env = true
-    file = File.read('/tmp/envfile').strip
+    raw = File.read('/tmp/envfile').strip
   else
     custom_env = false
     file = ENV['ENVFILE'] || defaultEnvFile
   end
-
   dotenv = begin
     # https://regex101.com/r/cbm5Tp/1
     dotenv_pattern = /^(?:export\s+|)(?<key>[[:alnum:]_]+)\s*=\s*((?<quote>["'])?(?<val>.*?[^\\])\k<quote>?|)$/
 
-    path = File.expand_path(File.join(envs_root, file.to_s))
-    if File.exist?(path)
-      raw = File.read(path)
-    elsif File.exist?(file)
-      raw = File.read(file)
-    else
-      defaultEnvPath = File.expand_path(File.join(envs_root, "#{defaultEnvFile}"))
-      unless File.exist?(defaultEnvPath)
-        # try as absolute path
-        defaultEnvPath = defaultEnvFile
+    unless custom_env
+      path = File.expand_path(File.join(envs_root, file.to_s))
+      if File.exist?(path)
+        raw = File.read(path)
+      elsif File.exist?(file)
+        raw = File.read(file)
+      else
+        defaultEnvPath = File.expand_path(File.join(envs_root, "#{defaultEnvFile}"))
+        puts defaultEnvPath
+        unless File.exist?(defaultEnvPath)
+          # try as absolute path
+          defaultEnvPath = defaultEnvFile
+        end
+        raw = File.read(defaultEnvPath)
       end
-      raw = File.read(defaultEnvPath)
     end
 
     raw.split("\n").inject({}) do |h, line|
@@ -47,11 +49,11 @@ def read_dot_env(envs_root)
       val = m[:val].to_s.gsub('"', '\"')
       h.merge(key => val)
     end
-    rescue Errno::ENOENT
+    rescue Errno::ENOENT => e
       puts('**************************')
       puts('*** Missing .env file ****')
       puts('**************************')
       return [{}, false] # set dotenv as an empty hash
   end
   [dotenv, custom_env]
-end
\ No newline at end of file
+end
```

Use `patch-package` to build your own patch

**Comment by SameeraMadushan** [comment] 2020-11-03 17:11
> It was not very clear from [README instructions](https://github.com/luggit/react-native-config#availability-in-build-settings-and-infoplist) where to add the script to generate `tmp.xcconfig`, so I mistakenly added it to the Build Phases under my application target. As it turned out it was too late: `Info.plist` is copied to the BUILD_DIR as a first step of the build and `tmp.xcconfig` is generated after that. As a result on the first build values from the `tmp.xcconfig` are not picked up and changes to the `.env` file are only picked up by the second build after the change is made.
> 
> The correct place where to add `BuildXCConfig.rb` is in Edit scheme... -> Build -> Pre-actions. Also make sure to select your target for "Provide build settings from".
> 
> <img alt="image" width="896" src="https://user-images.githubusercontent.com/823594/95124673-0fe14180-0754-11eb-85f3-7cfffe94c493.png">
> 
> Otherwise the approach seems to work correctly and you don't need to make loads of manual work as described in [#391 (comment)](https://github.com/luggit/react-native-config/issues/391#issuecomment-632331803).
> 
> PS Note that variables don't have `RNC_` prefix as with the legacy approach involving the `Info.plist` preprocessing.
> 
> **UPD**
> 
> Apparently one needs to setup same Pre-Action for the Archive schema, so values are available during the Archive build. And likely for every single schema you use. So I decided to to run this script manually before invoking Xcode to avoid maintaining same code in multiple places.

This worked for me as well. Im developing with multiple targets (dev, stage, prod). So I had to add Pre-actions to every target.

**Comment by adrach** [comment] 2021-01-08 04:56
leaving here a note in case someone else has the same issue
I was still having an issue with Info.plist not being processed correctly when building in bitrise
I have pre-action defined in both "build" and "archive"
Running manually after `npm install` before the build step solves the issue

```
#!/usr/bin/env bash
./node_modules/react-native-config/ios/ReactNativeConfig/BuildXCConfig.rb . ios/tmp.xcconfig 
```

**Comment by Andarius** [comment] 2021-04-19 19:00
@adrach when running this commande manually, how do you determine what the BUILD_DIR used by the script is ?
